name: example
description:  max_size_text example
version: 1.0.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  max_size_text:
    path: ../

flutter:
  uses-material-design: true