name: max_size_text
description: Maximize size of Flutter text given available real-estate.
version: 0.0.4
author: Peter Alvin <github_public@onlyup.com>
homepage: https://github.com/remoteportal/max_size_text

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: