name: max_size_text
description: Maximize size of Flutter text given available real-estate, including vertical, with the intention of filling a space.
version: 1.0.9
homepage: https://github.com/remoteportal/max_size_text

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: